### ISSUE TITLE
Export JMX metrics for monitoring performance

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/RADAR-Gateway#43]
By exporting some JMX metrics, we could use Prometheus to monitor things like CPU used / latency on parsing the request, forwarding the request, and forwarding the response.

@k1-hedayati feel free to update this issue.

**Comment by ghost** [comment]
Having some internal metrics would be useful, in one of the load testing scenarios response time for radar gateway was about 10 seconds while there were enough CPU and memory available. 
I haven't looked at the JMX metrics so I don't know if they are enough for monitoring gateway or not.

**Edit:** Especially for auto-scaling we need a metric that we can scale the gateway based on that
